language: node_js

cache:
  directories:
  - "~/.npm"

os:
  - linux

node_js:
  - '12'
  - '10'

services: mongodb

env:
  global:
  - NODE_ENV=tests
  - DATABASE_URL=mongodb://127.0.0.1/star
  - DATABASE_URL_TESTS=mongodb://127.0.0.1/star_test
  - PORT=8080
  - JWT_KEY=221b368d7f5f597867f525971f28ff75
  - JWT_EXPIRATION_TIME='30m'

branches:
  only:
  - master
  - deploy

deploy:
  provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  secure: $SECURE
  bucket: starHrd
  application: StarHrd
  deployment_group: starHrd
  region: ap-southeast-1