language: node_js

cache:
  directories:
  - ~/.npm

os:
  - linux

node_js:
  - '8'
  - '10'
  - '12'

services: mongodb

env:
  global:
    - NODE_ENV=tests
    - DATABASE_URL=mongodb://127.0.0.1/star
    - DATABASE_URL_TESTS=mongodb://127.0.0.1/star_test
    - PORT=8080
    - JWT_KEY=221b368d7f5f597867f525971f28ff75
    - JWT_EXPIRATION_TIME='30m'

branches:
  only:
    - master
    - deploy

jobs:
  include: 
    if: branch = deploy
    - stage: test
      script: npm test
    - stage: deploy
      script: npm run deploy

cache:
  directories:
    - ~/.npm