language: node_js

cache:
  directories:
  - "~/.npm"

os:
  - linux

node_js:
  - '12'
  - '10'

services: mongodb

env:
  global:
  - NODE_ENV=tests
  - DATABASE_URL=mongodb://127.0.0.1/star
  - DATABASE_URL_TESTS=mongodb://127.0.0.1/star_test
  - PORT=8080
  - JWT_KEY=221b368d7f5f597867f525971f28ff75
  - JWT_EXPIRATION_TIME='30m'

branches:
  only:
  - master
  - deploy

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  provider: s3
  access_key_id: AKIA2TOED2ZWOUAWRKGK
  secret_access_key: $AWS_SECRET_KEY
    secure: 0gLC1vcacRl7l/kHHE1kqfSlEmlsEovAr+ubj5IebByuAJnm8d/nO38Oeta2OgI4gIFXwxtmHA0RIiUC6gOu8CB2qqDzHjLQ6o3AqzEbVCVz0k8U5GVoTlm3NPQ6cZfvUvvofJ/YCZsGHKu7BKAAsGP9ROE/QlsdfgXuK7MQtngwgUDoSPZWVVXbVluDFDZw+55IFBZ6oIy5WOSzyYcRYbxb8Rd6vkPDHkA1S0AsQXLHE80Wsz4mKkQUMA/XF0CfajzH0Zk/PvH+5OuKdgqNN/JlM8XgnKT7O952QSFaqK9QkD6rkOltUtktfCXesH40WObWHkOh21Ses1hPm1lKWte5n3cbrcVlXsKC0y0MGE3aqD9B5wZDsjqieQbzPjeP6dopM+cc1rDqFb1kEHqISTxXpzelEEd4mGQoFZu5A89733/ZLeY0K3kV+jWdtWX5+o7U/Vx+DInGnMtCP8mcsiLrCMMEhP4dld+jJY2X11Pzj5l0qDEvF28Cii/i9b7lf3KzqShRzGkELurE0HHsX08kaj2G9IfBM/a8prjT6hFhfqA6pPze57zZ7i+50AU103kSInL6RUaQz8VMIeuDkmwUN1HSV0j9y5DnCuUqCu0syn+2wuzLkNijr0i84vT9tZUTuaAJh08EA20FqfqM3PrZoDXRuWD/9wBxJCTLZ0w=
  bucket: starHrd
  # local-dir: arifai/star
  upload-dir: arifai/star
  skip_cleanup: true
  on:
    repo: arifai/star
    branch: deploy
  # - provider: codedeploy
  #   access_key_id: AKIA2TOED2ZWOUAWRKGK
  #   secret_access_key: $AWS_SECRET_KEY
  #   bucket: starHrd
  #   key: latest.zip
  #   bundle_type: zip
  #   application: StarHrd
  #   deployment_group: Travis