version: 2
jobs:
  build:
    branches:
      only:
        - master
        - deploy

    docker:
      - image: circleci/node:10.16.2
      - image: circleci/mongo:4.0-xenial-ram

    add_ssh_keys:
      fingerprints:
        - "33:a5:c5:02:37:63:00:b9:d5:0a:bf:be:3b:2b:e5:c0"
    
    working_directory: ~/ahmadrifai

    environment:
      NODE_ENV: tests
      DATABASE_URL: mongodb://127.0.0.1/star
      DATABASE_URL_TESTS: mongodb://127.0.0.1/star_test
      PORT: 8080
      JWT_KEY: 221b368d7f5f597867f525971f28ff75
      JWT_EXPIRATION_TIME: '10m'

    steps:
      - checkout
      - run: 
          name: Setup
          command: | 
            chmod 755 deploy.sh
            ssh-keyscan $HOST >> ~/.ssh/known_hosts

      - run: 
          name: Install module
          command: npm ci

      - run: 
          name: Tests
          command: npm test
      
      - run:
          name: Deploy
          command: ./deploy.sh