version: 2
jobs:
  build:
    branches:
      only:
        - master
        
    working_directory: ~/star-hrd

    add_ssh_keys:
      fingerprints:
        - "e4:e3:af:48:75:d6:7e:50:90:23:5a:6e:23:8c:57:76"

    docker:
      - image: circleci/node:10.19.0
      - image: mongo:4.2.3
    
    # Setup environmet variables
    environment:
      NODE_ENV: tests
      DATABASE_URL: mongodb://127.0.0.1/star
      DATABASE_URL_TESTS: mongodb://127.0.0.1/star_test
      PORT: 8080
      JWT_KEY: 221b368d7f5f597867f525971f28ff75
      JWT_EXPIRATION_TIME: '15m'

    steps:
      - checkout
      
      - run:
          name: Setup
          command: | 
            chmod 755 deploy.sh
            ssh-keyscan $HOST >> ~/.ssh/known_hosts

      - run:
          name: Check NPM Version
          command: npm --version
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
    
      - run: 
          name: Run Test & Coverage
          command: npm run test:cover

      - run:
          name: Run Deploy
          command: npm run deploy