version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.2
    working_directory: ~/public
    steps:
      - checkout
      - run: sudo npm i -g npm@latest
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test